### ISSUE TITLE
your website is not working

### ISSUE THREAD

**Issue by yash3056** [kaushalpowar/talk_to_pdf#2]
![image](https://github.com/kaushalpowar/talk_to_pdf/assets/89018058/26218a27-5dc9-4631-9eef-761bd4f010f3)
![image](https://github.com/kaushalpowar/talk_to_pdf/assets/89018058/0a15a680-12fc-4fbc-af9e-6b86657d520f)

**Comment by kaushalpowar** [comment]
Thank you so much @yash3056  🙂
I just fixed the error. I was due the package name changes from llama-index.
